# ============= Profile: local (docker-compose) =============

# ============= CORS =============
cors.allowed-origins=http://localhost:5173,https://localhost

# ============= Timezone =============
clock.timezone=Europe/Brussels

# ============= Logging =============
logging.level.villanidev.berlinclock=INFO
logging.level.villanidev.berlinclock.api.controller=DEBUG
logging.level.villanidev.berlinclock.api.exception=WARN

# ============= Actuator =============
management.endpoint.health.show-details=always
